// Code generated by protoc-gen-go.
// source: echo.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	echo.proto

It has these top-level messages:
	AddIn
	AddOut
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgID int32

const (
	MsgID_UNKNOW MsgID = 0
	MsgID_ADD    MsgID = 1
)

var MsgID_name = map[int32]string{
	0: "UNKNOW",
	1: "ADD",
}
var MsgID_value = map[string]int32{
	"UNKNOW": 0,
	"ADD":    1,
}

func (x MsgID) String() string {
	return proto.EnumName(MsgID_name, int32(x))
}
func (MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AddIn struct {
	A int64 `protobuf:"varint,1,opt,name=A" json:"A,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=B" json:"B,omitempty"`
}

func (m *AddIn) Reset()                    { *m = AddIn{} }
func (m *AddIn) String() string            { return proto.CompactTextString(m) }
func (*AddIn) ProtoMessage()               {}
func (*AddIn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddIn) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *AddIn) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type AddOut struct {
	C int64 `protobuf:"varint,3,opt,name=C" json:"C,omitempty"`
}

func (m *AddOut) Reset()                    { *m = AddOut{} }
func (m *AddOut) String() string            { return proto.CompactTextString(m) }
func (*AddOut) ProtoMessage()               {}
func (*AddOut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddOut) GetC() int64 {
	if m != nil {
		return m.C
	}
	return 0
}

func init() {
	proto.RegisterType((*AddIn)(nil), "main.AddIn")
	proto.RegisterType((*AddOut)(nil), "main.AddOut")
	proto.RegisterEnum("main.MsgID", MsgID_name, MsgID_value)
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x52, 0xe6, 0x62,
	0x75, 0x4c, 0x49, 0xf1, 0xcc, 0x13, 0xe2, 0xe1, 0x62, 0x74, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0e, 0x62, 0x74, 0x04, 0xf1, 0x9c, 0x24, 0x98, 0x20, 0x3c, 0x27, 0x25, 0x31, 0x2e, 0x36, 0xc7,
	0x94, 0x14, 0xff, 0xd2, 0x12, 0x90, 0xb8, 0xb3, 0x04, 0x33, 0x44, 0xdc, 0x59, 0x4b, 0x86, 0x8b,
	0xd5, 0xb7, 0x38, 0xdd, 0xd3, 0x45, 0x88, 0x8b, 0x8b, 0x2d, 0xd4, 0xcf, 0xdb, 0xcf, 0x3f, 0x5c,
	0x80, 0x41, 0x88, 0x9d, 0x8b, 0xd9, 0xd1, 0xc5, 0x45, 0x80, 0x31, 0x89, 0x0d, 0x6c, 0x8f, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x8b, 0xb8, 0xc3, 0x75, 0x00, 0x00, 0x00,
}
