// Code generated by protoc-gen-go.
// source: services.proto
// DO NOT EDIT!

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	services.proto

It has these top-level messages:
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceID int32

const (
	ServiceID_SERVICE1 ServiceID = 0
)

var ServiceID_name = map[int32]string{
	0: "SERVICE1",
}
var ServiceID_value = map[string]int32{
	"SERVICE1": 0,
}

func (x ServiceID) String() string {
	return proto.EnumName(ServiceID_name, int32(x))
}
func (ServiceID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("services.ServiceID", ServiceID_name, ServiceID_value)
}

func init() { proto.RegisterFile("services.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 72 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xb5, 0x24,
	0xb9, 0x38, 0x83, 0x21, 0x6c, 0x4f, 0x17, 0x21, 0x1e, 0x2e, 0x8e, 0x60, 0xd7, 0xa0, 0x30, 0x4f,
	0x67, 0x57, 0x43, 0x01, 0x86, 0x24, 0x36, 0xb0, 0x5a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x65, 0x78, 0xd0, 0xf6, 0x3d, 0x00, 0x00, 0x00,
}
